### PR TITLE
Solves Issue 8 (missing extension files)

### PR DESCRIPTION
**Pull request by RibeiroAna**

### CODE REVIEW

**Comment by davehunt** [comment]
r+ thanks @RibeiroAna! could you squash the commits so there's just one, then it's ready to merge! :D

**Comment by RibeiroAna** [comment]
Done :smile:

**Comment by davehunt** [comment]
Awesome. I reworded the commit message, and pushed it to master here: https://github.com/davehunt/pytest-variables/commit/59548fb7ab82ddb138140658455c44c54d95a776

**Comment by davehunt** [comment]
I've released [version 1.4](https://pypi.python.org/pypi/pytest-variables/1.4) with your enhancement!

**Pull request closed without merging**
